### ISSUE TITLE
Better xor version

### ISSUE THREAD

**Issue by gettalong** [fny/clean_pbkdf2#1]
Hi,

you might wanna optimize the `xor!` function at https://github.com/fny/clean_pbkdf2/blob/master/lib/pbkdf2/engine.rb#L80.

Have a look at the better version at https://github.com/CodeMonkeySteve/fast_xor/issues/10 which performs much better. And should perform even more so compared to your version because you are creating at least four arrays unnecessarily.

Cheers,
  Thomas

**Comment by fny** [comment]
Awsome!

I'm actually swapping the Ruby xor here with the implementation in my [xorcist gem](https://github.com/fny/xorcist) since that has built in Java extensions too. I've updated the benchmark there to use [your version](https://github.com/fny/xorcist/blob/master/bin/benchmark#L7).

Thanks!
Faraz
